// LunaCode Main JavaScript

/**
 * Define the custom "Move Forward" block in Hebrew.
 */
Blockly.Blocks['move_forward'] = {
  init: function() {
    this.appendValueInput("STEPS")
        .setCheck("Number")
        .appendField("צעד קדימה");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
    this.setTooltip("הזז את הדמות קדימה");
    this.setHelpUrl("");
  }
};

/**
 * Define the JavaScript generator for the "Move Forward" block.
 */
Blockly.JavaScript['move_forward'] = function(block) {
  const steps = Blockly.JavaScript.valueToCode(block, 'STEPS', Blockly.JavaScript.ORDER_ATOMIC) || 0;
  // Generate a function call that will be executed.
  const code = `moveCharacter(${steps});\n`;
  return code;
};

// Keep a reference to the workspace.
let workspace;

/**
 * Initializes the Blockly workspace and sets up event listeners.
 */
function init() {
    const blocklyDiv = document.getElementById('blockly-div');
    const runButton = document.getElementById('run-button');

    // Define the toolbox.
    const toolbox = {
        'kind': 'flyoutToolbox',
        'contents': [
            {
                'kind': 'block',
                'type': 'move_forward'
            },
            {
                'kind': 'block',
                'type': 'math_number',
                'fields': {
                    'NUM': 1
                }
            }
        ]
    };

    workspace = Blockly.inject(blocklyDiv, {
        toolbox: toolbox,
        rtl: true,
        renderer: 'zelos',
        theme: Blockly.Themes.Default,
        zoom: {
            controls: true,
            wheel: true,
            startScale: 1.0,
            maxScale: 3,
            minScale: 0.3,
            scaleSpeed: 1.2
        },
        trashcan: true
    });

    // Resize Blockly on window resize
    const onresize = function(e) {
        Blockly.svgResize(workspace);
    };
    window.addEventListener('resize', onresize, false);
    onresize();

    // Add event listener to the run button
    runButton.addEventListener('click', runCode);
}

/**
 * Executes the code generated by Blockly.
 */
function runCode() {
    // Generate JavaScript code from the workspace.
    const code = Blockly.JavaScript.workspaceToCode(workspace);

    // Execute the code.
    try {
        eval(code);
    } catch (e) {
        console.error('Error executing code:', e);
        alert('An error occurred while running the code.');
    }
}

/**
 * Moves the character on the stage.
 * @param {number} steps - The number of steps to move.
 */
function moveCharacter(steps) {
    const character = document.getElementById('character');
    if (character) {
        // This is a simplified movement.
        // In a real scenario, this would be more complex.
        const currentLeft = character.style.left ? parseFloat(character.style.left) : 50;
        // In RTL, moving "forward" means moving left.
        const newLeft = currentLeft - (steps * 10); // Move 10px per step
        character.style.left = `${newLeft}%`;
    }
}

// Initialize the application when the window loads
window.addEventListener('load', init);
